-- AlterTable
ALTER TABLE "MfgBottling" DROP COLUMN "bottleSize",
DROP COLUMN "bottledAt",
DROP COLUMN "bottledByName",
DROP COLUMN "bottlesIssued",
DROP COLUMN "bottlesReturned",
DROP COLUMN "bottlesUsed",
DROP COLUMN "capsIssued",
DROP COLUMN "capsReturned",
DROP COLUMN "capsulesReceived",
DROP COLUMN "capsulesRemaining",
DROP COLUMN "capsulesUsed",
DROP COLUMN "damagedBottles",
DROP COLUMN "damagedCaps",
DROP COLUMN "damagedDesiccants",
DROP COLUMN "desiccantsIssued",
DROP COLUMN "desiccantsReturned",
DROP COLUMN "expectedBottles",
DROP COLUMN "filledBottles",
DROP COLUMN "qcSampleBottles",
DROP COLUMN "rejectedBottles",
DROP COLUMN "remarks",
DROP COLUMN "retentionBottles",
ADD COLUMN     "avgCapsuleFullWeightMg" DOUBLE PRECISION,
ADD COLUMN     "bottleUsed" INTEGER,
ADD COLUMN     "bottlesProduced" INTEGER,
ADD COLUMN     "capsuleReceivedKg" DOUBLE PRECISION,
ADD COLUMN     "checkedAt" TIMESTAMP(3),
ADD COLUMN     "checkedByName" TEXT,
ADD COLUMN     "comments" TEXT,
ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "completedByName" TEXT,
ADD COLUMN     "plannedQuantityBottles" INTEGER,
ADD COLUMN     "totalCapsuleBulkWeightKg" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MfgEncapsulation" DROP COLUMN "blendReceivedKg",
DROP COLUMN "blendRemainingKg",
DROP COLUMN "blendReturnedKg",
DROP COLUMN "blendUsedKg",
DROP COLUMN "brokenCapsules",
DROP COLUMN "capsuleColour",
DROP COLUMN "capsuleLot",
DROP COLUMN "capsuleSize",
DROP COLUMN "capsulesIssued",
DROP COLUMN "capsulesReturned",
DROP COLUMN "capsulesUsed",
DROP COLUMN "encapsulatedAt",
DROP COLUMN "encapsulatedByName",
DROP COLUMN "expectedCapsules",
DROP COLUMN "finishedCapsuleWeightKg",
DROP COLUMN "goodCapsules",
DROP COLUMN "machineRejects",
DROP COLUMN "powderWasteKg",
DROP COLUMN "rejectedCapsules",
DROP COLUMN "remarks",
DROP COLUMN "retentionCapsules",
DROP COLUMN "sampleCapsules",
DROP COLUMN "samplingKg",
DROP COLUMN "targetFillWeightMg",
ADD COLUMN     "avgCapsuleFillWeightMg" DOUBLE PRECISION,
ADD COLUMN     "avgCapsuleFullWeightMg" DOUBLE PRECISION,
ADD COLUMN     "avgCapsuleLengthMm" DOUBLE PRECISION,
ADD COLUMN     "avgDisintegrationMinutes" INTEGER,
ADD COLUMN     "avgDisintegrationSeconds" INTEGER,
ADD COLUMN     "capsuleSamplesKg" DOUBLE PRECISION,
ADD COLUMN     "capsulesProducedKg" DOUBLE PRECISION,
ADD COLUMN     "checkedAt" TIMESTAMP(3),
ADD COLUMN     "checkedByName" TEXT,
ADD COLUMN     "comments" TEXT,
ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "completedByName" TEXT,
ADD COLUMN     "disintegrationResult" TEXT,
ADD COLUMN     "issuedBulkBlendKg" DOUBLE PRECISION,
ADD COLUMN     "rejectCapsulesKg" DOUBLE PRECISION,
ADD COLUMN     "rejectPowderKg" DOUBLE PRECISION,
ADD COLUMN     "targetCapsuleFillWeightMg" DOUBLE PRECISION;
